# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a58628480df00ca65d9ebf32e2f5f41089f7338adf10d7f6e1a0771deb826fc30726125f914bbfa26412dcac96b707e8fbaf4f0d9a7334731d11aabfccea5a

test:
  secret_key_base: 5b2c5481cf4de6be2de29bee3b876ef860e49e002c378e53011d5b6176eca7d144effc4a8f0c21fde674067cd799d170eb9ddc37b3333a290077dc6ae5c02267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
